# medical_report_generator.py
from datetime import datetime
import json
import os
from typing import Dict, List, Any

class MedicalReportGenerator:
    """
    Generate comprehensive medical reports from AI analysis results
    """
    
    def __init__(self, template_path=None):
        self.templates = self._load_templates(template_path)
        
    def _load_templates(self, template_path):
        """Load report templates"""
        base_templates = {
            'standard': self._standard_template(),
            'detailed': self._detailed_template(),
            'urgent': self._urgent_template()
        }
        return base_templates
    
    def _standard_template(self):
        return {
            'header': "MEDICAL IMAGING DIAGNOSTIC REPORT",
            'sections': [
                'patient_info',
                'clinical_history',
                'imaging_findings', 
                'ai_analysis',
                'impression',
                'recommendations'
            ]
        }
    
    def _detailed_template(self):
        return {
            'header': "COMPREHENSIVE MEDICAL IMAGING REPORT",
            'sections': [
                'patient_info',
                'clinical_history',
                'exam_details',
                'comparison',
                'imaging_findings',
                'ai_analysis',
                'biomarkers',
                'impression',
                'recommendations',
                'limitations'
            ]
        }
    
    def _urgent_template(self):
        return {
            'header': "URGENT MEDICAL IMAGING REPORT",
            'sections': [
                'patient_info',
                'critical_findings',
                'ai_analysis',
                'urgent_recommendations',
                'contact_info'
            ]
        }
    
    def generate_report(self, analysis_data: Dict, patient_info: Dict, 
                       template_type: str = 'standard') -> str:
        """
        Generate medical report from analysis data
        """
        template = self.templates.get(template_type, self.templates['standard'])
        
        report_parts = []
        
        # Header
        report_parts.append(f"{'='*60}")
        report_parts.append(f"{template['header']:^60}")
        report_parts.append(f"{'='*60}")
        report_parts.append(f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        report_parts.append("")
        
        # Sections
        for section in template['sections']:
            section_content = self._generate_section(section, analysis_data, patient_info)
            if section_content:
                report_parts.append(section_content)
                report_parts.append("")
        
        # Footer
        report_parts.append(f"{'-'*60}")
        report_parts.append("Generated by Medical AI Diagnostic System v2.1.0")
        report_parts.append("This report should be interpreted by qualified healthcare professionals")
        
        return '\n'.join(report_parts)
    
    def _generate_section(self, section: str, analysis_data: Dict, patient_info: Dict) -> str:
        """Generate individual section content"""
        
        if section == 'patient_info':
            return self._patient_info_section(patient_info)
        
        elif section == 'clinical_history':
            return self._clinical_history_section(patient_info)
        
        elif section == 'imaging_findings':
            return self._imaging_findings_section(analysis_data)
        
        elif section == 'ai_analysis':
            return self._ai_analysis_section(analysis_data)
        
        elif section == 'biomarkers':
            return self._biomarkers_section(analysis_data)
        
        elif section == 'impression':
            return self._impression_section(analysis_data)
        
        elif section == 'recommendations':
            return self._recommendations_section(analysis_data)
        
        elif section == 'critical_findings':
            return self._critical_findings_section(analysis_data)
        
        elif section == 'urgent_recommendations':
            return self._urgent_recommendations_section(analysis_data)
        
        return ""
    
    def _patient_info_section(self, patient_info: Dict) -> str:
        section = "PATIENT INFORMATION:\n"
        section += f"  Name: {patient_info.get('name', 'N/A')}\n"
        section += f"  Patient ID: {patient_info.get('patient_id', 'N/A')}\n"
        section += f"  Age: {patient_info.get('age', 'N/A')}\n"
        section += f"  Gender: {patient_info.get('gender', 'N/A')}\n"
        section += f"  Date of Birth: {patient_info.get('birth_date', 'N/A')}"
        return section
    
    def _clinical_history_section(self, patient_info: Dict) -> str:
        section = "CLINICAL HISTORY:\n"
        section += f"  Presenting Condition: {patient_info.get('condition', 'N/A')}\n"
        section += f"  Referring Physician: {patient_info.get('physician', 'Not specified')}"
        return section
    
    def _imaging_findings_section(self, analysis_data: Dict) -> str:
        section = "IMAGING FINDINGS:\n"
        section += f"  Primary Diagnosis: {analysis_data.get('primary_diagnosis', 'N/A')}\n"
        section += f"  Confidence Score: {analysis_data.get('confidence_score', 0):.2%}\n"
        section += f"  Risk Level: {analysis_data.get('risk_level', 'N/A')}"
        return section
    
    def _ai_analysis_section(self, analysis_data: Dict) -> str:
        section = "AI ANALYSIS RESULTS:\n"
        section += f"  Model: {analysis_data.get('model_version', 'N/A')}\n"
        section += f"  Processing Time: {analysis_data.get('processing_time', 0):.2f} seconds\n"
        section += f"  Analysis Date: {analysis_data.get('analysis_date', 'N/A')}"
        return section
    
    def _biomarkers_section(self, analysis_data: Dict) -> str:
        biomarkers = analysis_data.get('biomarkers', {})
        if not biomarkers:
            return ""
        
        section = "QUANTITATIVE BIOMARKERS:\n"
        
        for category, metrics in biomarkers.items():
            section += f"  {category.replace('_', ' ').title()}:\n"
            for metric, value in metrics.items():
                if isinstance(value, float):
                    section += f"    {metric}: {value:.3f}\n"
                else:
                    section += f"    {metric}: {value}\n"
        
        return section.rstrip()
    
    def _impression_section(self, analysis_data: Dict) -> str:
        section = "IMPRESSION:\n"
        diagnosis = analysis_data.get('primary_diagnosis', '')
        confidence = analysis_data.get('confidence_score', 0)
        
        if confidence > 0.85:
            certainty = "High certainty"
        elif confidence > 0.70:
            certainty = "Moderate certainty"
        else:
            certainty = "Low certainty"
        
        section += f"  {certainty} of {diagnosis.lower()} based on AI analysis."
        return section
    
    def _recommendations_section(self, analysis_data: Dict) -> str:
        recommendations = analysis_data.get('recommendations', [])
        if not recommendations:
            return "RECOMMENDATIONS:\n  Clinical correlation advised."
        
        section = "RECOMMENDATIONS:\n"
        for i, rec in enumerate(recommendations, 1):
            section += f"  {i}. {rec}\n"
        
        return section.rstrip()
    
    def _critical_findings_section(self, analysis_data: Dict) -> str:
        section = "CRITICAL FINDINGS:\n"
        section += f"  ⚠️  {analysis_data.get('primary_diagnosis', 'Critical finding')}\n"
        section += f"  Confidence: {analysis_data.get('confidence_score', 0):.2%}\n"
        section += f"  Risk Level: {analysis_data.get('risk_level', 'HIGH')}"
        return section
    
    def _urgent_recommendations_section(self, analysis_data: Dict) -> str:
        section = "URGENT RECOMMENDATIONS:\n"
        section += "  🚨 IMMEDIATE CLINICAL ATTENTION REQUIRED\n"
        
        for rec in analysis_data.get('recommendations', []):
            section += f"  • {rec}\n"
        
        section += "  Please contact referring physician immediately."
        return section

# Example usage
if __name__ == "__main__":
    generator = MedicalReportGenerator()
    
    sample_analysis = {
        'primary_diagnosis': 'Suspicious Lung Nodule',
        'confidence_score': 0.82,
        'risk_level': 'Medium',
        'model_version': 'Hybrid-CNN-Transformer-v2.1',
        'processing_time': 2.34,
        'analysis_date': '2024-01-15 14:30:00',
        'biomarkers': {
            'texture_analysis': {
                'entropy': 3.2,
                'contrast': 0.45,
                'homogeneity': 0.67
            }
        },
        'recommendations': [
            "Further diagnostic workup advised",
            "Multidisciplinary consultation recommended",
            "Consider biopsy if clinically indicated"
        ]
    }
    
    sample_patient = {
        'name': 'John Smith',
        'patient_id': 'PAT_001',
        'age': 45,
        'gender': 'Male',
        'birth_date': '1978-05-15',
        'condition': 'Suspicious Lung Nodule',
        'physician': 'Dr. Garcia'
    }
    
    report = generator.generate_report(sample_analysis, sample_patient, 'standard')
    print(report)
